### ISSUE TITLE
Maybe reconsier !=

### ISSUE THREAD

**Issue by joinr** [xadecimal/procedural#1]
I think this would trip up most people coming from imperative langs

```clojure
(!= x 20)
```

I would have suggested `:=` but that's a keyword (F# uses it for ref cells value changes).

F# and surprisingly R use `<-` to denote mutable value setting too.  I would probably lobby for that over something that defies expectations.

Food for thought :)

**Comment by didibus** [comment]
I went with `=!`, because I find there's starting to be a lot of "arrow" like symbols in Clojure and `<-` might get too confusing with all the others.
